# Generated by Django 2.0 on 2017-12-18 15:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
