# Generated by Django 2.0 on 2017-12-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_poi_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poi',
            old_name='photos',
            new_name='gallery',
        ),
    ]
