# Generated by Django 2.0 on 2017-12-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='average_rating',
        ),
    ]
