# Generated by Django 2.0 on 2017-12-19 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_poi_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='rating',
        ),
        migrations.AddField(
            model_name='poi',
            name='comments',
            field=models.ManyToManyField(related_name='usercomments', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poi',
            name='ratings',
            field=models.ManyToManyField(related_name='userratings', through='api.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_comments', to='api.POI'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_ratings', to='api.POI'),
        ),
    ]
