# Generated by Django 2.0 on 2017-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171219_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='severity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
