# Generated by Django 2.0 on 2017-12-20 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20171220_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='visited',
            field=models.ManyToManyField(related_name='uservisits', through='api.Visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
