# Generated by Django 2.0 on 2017-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171221_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('ACE', 'Aceptada'), ('PEN', 'Pendiente'), ('REC', 'Rechazada')], default='PEN', max_length=50),
        ),
    ]
