# Generated by Django 2.0 on 2018-01-02 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poims', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Positivo'), (-1, 'Negativo')])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('poim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='poims.POIM')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'poim')},
        ),
    ]
